{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_stock\",\"fact_stock_price\",\"_Measure Table\",\"Data Updated DateTime\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-CA",
    "cultures": [
      {
        "name": "en-CA",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "relationships": [
      {
        "name": "12f521c8-527b-0847-e4c7-531714e0e2b5",
        "fromColumn": "symbol",
        "fromTable": "fact_stock_price",
        "toColumn": "symbol",
        "toTable": "dim_stock"
      },
      {
        "name": "c90dae01-81f8-2de7-82b4-fb464319b9e3",
        "fromColumn": "symbol",
        "fromTable": "dim_stock",
        "toColumn": "symbol",
        "toTable": "Industry"
      },
      {
        "name": "46d32123-b072-631e-dfcd-7e5444cfc0a5",
        "fromColumn": "date",
        "fromTable": "fact_stock_price",
        "toColumn": "Date",
        "toTable": "Date"
      }
    ],
    "sourceQueryCulture": "en-CA",
    "tables": [
      {
        "name": "dim_stock",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "symbol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ef52ada-f2c7-467b-9203-9fdd5e20f8c6",
            "sortByColumn": "SymbolSort",
            "sourceColumn": "symbol",
            "summarizeBy": "none"
          },
          {
            "name": "interval",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df7747c7-b6b2-4da5-910f-6eb6f54034c9",
            "sourceColumn": "interval",
            "summarizeBy": "none"
          },
          {
            "name": "currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc09f6d9-fbe0-47a3-9777-0e20af48526c",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "exchange_timezone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aaeecacb-ffd5-41a3-847c-b5f50b30c7b2",
            "sourceColumn": "exchange_timezone",
            "summarizeBy": "none"
          },
          {
            "name": "exchange",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87b58aa6-34fa-414f-9103-6cafd76e1d10",
            "sourceColumn": "exchange",
            "summarizeBy": "none"
          },
          {
            "name": "mic_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "daec1d02-3ddd-4e1b-bed7-979dc2bb5c15",
            "sourceColumn": "mic_code",
            "summarizeBy": "none"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d29ce57c-71f5-4212-8f32-8da77f8746a7",
            "sourceColumn": "type",
            "summarizeBy": "none"
          },
          {
            "name": "Industry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CALCULATE( max(Industry[Industry] ) )",
            "isDataTypeInferred": true,
            "lineageTag": "de00310c-957f-4e8b-9c34-ea0bdb327b55",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SymbolSort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "CALCULATE( max(Industry[Sort] ) )",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "1bea7fea-a584-411f-8731-1769f2f4592c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Logo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "expression": "CALCULATE( max(Industry[Logo] ) )",
            "isDataTypeInferred": true,
            "lineageTag": "31793248-5765-4043-b2b3-95ddbb11706b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "5ee11b9c-015a-4678-8af3-70529518c1a6",
        "partitions": [
          {
            "name": "dim_stock",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(\"adb-3615338042282873.13.azuredatabricks.net\", \"/sql/1.0/warehouses/a9bd9c6185df8880\", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    hive_metastore_Database = Source{[Name=\"hive_metastore\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = hive_metastore_Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    dim_stock_Table = gold_Schema{[Name=\"dim_stock\",Kind=\"Table\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dim_stock_Table, each ([symbol] <> \"ARKK\" and [symbol] <> \"EEM\" and [symbol] <> \"GOVT\" and [symbol] <> \"IWM\" and [symbol] <> \"VEA\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"created_date\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\"),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Duplicates\", each ([symbol] = \"AAPL\" or [symbol] = \"F\" or [symbol] = \"GS\" or [symbol] = \"JPM\" or [symbol] = \"MS\" or [symbol] = \"MSFT\" or [symbol] = \"NVDA\" or [symbol] = \"TM\" or [symbol] = \"TSLA\" or [symbol] = \"VOO\"))",
                "in",
                "    #\"Filtered Rows1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_stock_price",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "symbol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8640fb67-c994-48db-a584-89c7750157f8",
            "sourceColumn": "symbol",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0a698b35-dd71-46b7-89cc-f0494bf5be40",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "open",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "872322ba-9b98-4791-960e-0d5f8af43654",
            "sourceColumn": "open",
            "summarizeBy": "sum"
          },
          {
            "name": "high",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "56c2e68c-2ce6-4aa7-b8d7-a4916895bfb8",
            "sourceColumn": "high",
            "summarizeBy": "sum"
          },
          {
            "name": "low",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1ff84e30-fd3f-4160-ad9e-92d73b2bbe9b",
            "sourceColumn": "low",
            "summarizeBy": "sum"
          },
          {
            "name": "close",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "68ec3bc0-4622-4a65-bd67-a7d2dd8c464c",
            "sourceColumn": "close",
            "summarizeBy": "sum"
          },
          {
            "name": "volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8806bb75-aba3-4b0d-8462-5bb4ec9cbe27",
            "sourceColumn": "volume",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "2d49b5c8-885c-47b3-8119-13ee6700179c",
        "partitions": [
          {
            "name": "fact_stock_price",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(\"adb-3615338042282873.13.azuredatabricks.net\", \"/sql/1.0/warehouses/a9bd9c6185df8880\", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    hive_metastore_Database = Source{[Name=\"hive_metastore\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = hive_metastore_Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    fact_stock_price_Table = gold_Schema{[Name=\"fact_stock_price\",Kind=\"Table\"]}[Data],",
                "    #\"Sorted Rows\" = Table.Sort(fact_stock_price_Table,{{\"datetime\", Order.Ascending}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Sorted Rows\",{\"created_date\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"datetime\", \"date\"}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Renamed Columns\", {\"date\", \"symbol\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Duplicates\", each ([symbol] = \"AAPL\" or [symbol] = \"F\" or [symbol] = \"GS\" or [symbol] = \"JPM\" or [symbol] = \"MS\" or [symbol] = \"MSFT\" or [symbol] = \"NVDA\" or [symbol] = \"TM\" or [symbol] = \"TSLA\" or [symbol] = \"VOO\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "297326d0a9244128adb5f25b6b40e983"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "171c2eee-1edf-429a-a200-a50759840f12",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "908970e6-1b62-44af-ac67-165ed56bba69",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b679282f-6807-4810-912c-bde4bf76d203",
            "sourceColumn": "[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f7e5c0f4-bb00-4434-9404-a60de331e538",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "77bdad60-7288-4a31-91d2-d70b78fb7c44",
            "sourceColumn": "[Month Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9b515595-6642-412e-b7b0-8b53dcaeab0d",
            "sourceColumn": "[Day]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8ec34c9e-598e-4bfe-80a4-1206c4f16324",
            "sourceColumn": "[Month Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year-Quarter-Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d2fb2380-9d49-4458-85a3-9f32a23f16e5",
            "sourceColumn": "[Year-Quarter-Sort]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week Last Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "281e972f-9b35-4c6c-ad3b-2b5d941859d9",
            "sourceColumn": "[Week Last Day]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Date SID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f4a9c2c4-c215-4784-8433-344286f063c8",
            "sourceColumn": "[Date SID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsCurrentMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6cbf4b68-abf4-494f-97c6-923b31d9e44b",
            "sourceColumn": "[IsCurrentMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter-Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8c67608c-7073-40e6-a440-f72ba11f9883",
            "sortByColumn": "Year-Quarter-Sort",
            "sourceColumn": "[Quarter-Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year-Month Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "expression": "DATE('Date'[Year], 'Date'[Month] , 01)",
            "formatString": "yyyy-mm",
            "isDataTypeInferred": true,
            "lineageTag": "575657c0-6370-4f6f-aedc-048a29ec63b1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day of week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "22751c6b-a2f3-4300-a425-241eae213b29",
            "sortByColumn": "Day of week number",
            "sourceColumn": "[Day of week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of week number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b77f66e8-c804-4941-b210-91a6894986b4",
            "sourceColumn": "[Day of week number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "00ff3fe7-d2a0-4610-8ec6-d6ad8ca980a4",
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS (",
                "    CALENDAR(  date( 2000 ,1,1),  date( year(TODAY()), MONTH(TODAY()), day( EOMONTH(TODAY(),0) ) )     ),",
                "    \"Year\", YEAR([Date]),",
                "    \"Quarter\", \"Q\" & FORMAT([Date], \"Q\"),",
                "    \"Quarter-Year\", \"Q\" & FORMAT([Date], \"Q 'YY\"),",
                "    \"Month\", MONTH([Date]),",
                "    \"Month Name\", FORMAT([Date], \"mmm\"),",
                "    \"Day\", DAY([Date]),",
                "    \"Day of week number\", WEEKDAY([Date]),",
                "    \"Day of week\", FORMAT([Date], \"dddd\"),",
                "    \"Month Year\", FORMAT([Date], \"MMM 'YY\"),",
                "    \"Year-Quarter-Sort\", (YEAR([Date]) * 100) + QUARTER([Date]),",
                "    \"Week Last Day\", IF(",
                "                        YEAR([Date] - WEEKDAY([Date], 2) + 7) < YEAR([Date]),",
                "                        DATE(YEAR([Date]), 1, 1),",
                "                        [Date] - WEEKDAY([Date], 2) + 7",
                "                     ),",
                "    \"Date SID\", FORMAT([Date], \"YYYYMMDD\"), ",
                "    \"IsCurrentMonth\", if( YEAR([Date]) & \"-\" & FORMAT([Date], \"MM\") = YEAR( TODAY()) & \"-\" & FORMAT(TODAY(), \"MM\"),  \"Current Month\" , YEAR([Date]) & \"-\" & FORMAT([Date], \"MM\") )",
                "",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Measure Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "lineageTag": "c3f9021e-3dc1-4123-a10d-56bb09e470a2",
        "measures": [
          {
            "name": "First Open Value for Selected Period",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "_Open & Close for Date Range",
            "expression": [
              "",
              "  ",
              "",
              "var _var =  [NonBlank Open Date]  ",
              "var _selectedtimerange= [Selected Time Range] ",
              " ",
              " RETURN ",
              "var _result = CALCULATE( [Sum open] ,  'Date'[Date] = _var  ) ",
              "",
              " return ",
              " CALCULATE(  ",
              "_result, ",
              " 'CG Time Intelligence'[Name] = _selectedtimerange  )",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "43ddc182-828f-4fcc-9abe-30323f10be53"
          },
          {
            "name": "Sum Close",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "_Main Measures",
            "expression": "sum(fact_stock_price[close] ) ",
            "lineageTag": "117ced02-365c-48eb-9877-95aab521af79"
          },
          {
            "name": "Last Close Value for Selected Period",
            "displayFolder": "_Open & Close for Date Range",
            "expression": "CALCULATE( [Sum Close] ,  FILTER( all('Date'[Date]),  'Date'[Date] = [NonBlank Close Date] )  )  ",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1530a01e-1ff7-4638-a7ae-4c950529cdb1"
          },
          {
            "name": "GreenLine",
            "displayFolder": "Data Between Ranges",
            "expression": "if( [Last Close Value for Selected Period] - [First Open Value for Selected Period]  >= 0 , [Close for Selected Period] )",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "3ba6b4c9-82d1-481c-a7ee-2b9eb5b8d08a"
          },
          {
            "name": "RedLine",
            "displayFolder": "Data Between Ranges",
            "expression": [
              "",
              "",
              "  if( [Last Close Value for Selected Period] - [First Open Value for Selected Period]  < 0 , [Close for Selected Period] )  "
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c44aa33d-f425-4426-83a1-25ba99db8193"
          },
          {
            "name": "Text Stock Growth % For Selected Range",
            "displayFolder": "_Open & Close for Date Range",
            "expression": "FORMAT( [Stock Growth %] , \"+0.00%;-0.00%;0.00%\" )",
            "lineageTag": "e9832abf-a620-4962-9d83-1460dedb0e43"
          },
          {
            "name": "Color Stock Growth",
            "expression": "if( [Last Close Value for Selected Period] - [First Open Value for Selected Period]  >= 0 , \"#039520\" , \"#DD0012\" ) ",
            "lineageTag": "69190697-3aad-49f5-abcc-b57e99ac7ab6"
          },
          {
            "name": "Selected Time Range",
            "displayFolder": "_Selected Value",
            "expression": "SELECTEDVALUE('Time Range'[Range Name], \"30 Days\" ) ",
            "lineageTag": "3986032a-b43a-42c0-a338-402443d2ccfe"
          },
          {
            "name": "Close for Selected Period",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Data Between Ranges",
            "expression": [
              "",
              " ",
              " var selectedrange =  [Selected Time Range]",
              "",
              "return",
              "CALCULATE([Sum Close] , 'CG Time Intelligence'[Name] =  selectedrange)"
            ],
            "lineageTag": "139b71ba-ead7-44bb-bb07-a65592165e61"
          },
          {
            "name": "MinDate",
            "displayFolder": "_Main Measures",
            "expression": "min ('Date'[Date] )",
            "formatString": "General Date",
            "lineageTag": "19459998-fcbd-4a45-88db-e4a7440bb2ad"
          },
          {
            "name": "Max Date",
            "displayFolder": "_Main Measures",
            "expression": "max ('Date'[Date] )",
            "formatString": "General Date",
            "lineageTag": "166abdb3-7e5d-4e42-9ae4-8343c375b0c6"
          },
          {
            "name": "SelectedValues Symbol",
            "displayFolder": "_Selected Value",
            "expression": "SELECTEDVALUE( dim_stock[symbol])",
            "lineageTag": "c25723d3-36e5-4d6a-b9c8-3709c8f91d98"
          },
          {
            "name": "SelectedValues Exchange Name",
            "displayFolder": "_Selected Value",
            "expression": "SELECTEDVALUE( dim_stock[exchange])",
            "lineageTag": "2407f184-28d0-4846-92ce-8bd1698ca500"
          },
          {
            "name": "Sum open",
            "displayFolder": "_Main Measures",
            "expression": "sum(fact_stock_price[open])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1226036d-a86c-49b1-9b38-8b459790861d"
          },
          {
            "name": "NonBlank Open Date",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "displayFolder": "_Open & Close for Date Range",
            "expression": [
              "",
              "",
              "var selectedrange = [Selected Time Range]",
              "",
              "",
              "return ",
              " CALCULATE(  [MinDate]  , ",
              "FILTER(  all( 'Date') , [Sum open] > 0 ),",
              "'CG Time Intelligence'[Name] =  selectedrange ",
              "",
              ")  ",
              "",
              ""
            ],
            "formatString": "dd-mmm-yy",
            "lineageTag": "822e09f3-b16e-47e8-b539-6138ee1012fa"
          },
          {
            "name": "NonBlank Close Date",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "displayFolder": "_Open & Close for Date Range",
            "expression": [
              "",
              " ",
              "CALCULATE(  [Max Date]  , ",
              "FILTER( all('Date'), [Sum Close] > 0 ) )"
            ],
            "formatString": "dd-mmm-yy",
            "lineageTag": "b9cff263-a93b-4e3f-8f5c-32bdcde31ad5"
          },
          {
            "name": "Min Low",
            "displayFolder": "_Main Measures",
            "expression": "min(fact_stock_price[low] ) ",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "787c0654-53a2-4cc6-854e-b0200874fb83"
          },
          {
            "name": "Max High",
            "displayFolder": "_Main Measures",
            "expression": "max(fact_stock_price[high] )",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "8b07911f-fb22-46c5-a532-52382faa5187"
          },
          {
            "name": "AVG Volume",
            "displayFolder": "_Main Measures",
            "expression": "AVERAGE(fact_stock_price[volume])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d033a374-f552-427d-a04c-6ff9baf670c9"
          },
          {
            "name": "Money Invested",
            "displayFolder": "_Main Measures",
            "expression": "10000 ",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6ad71372-13fd-469b-9da1-56a15e916bcb"
          },
          {
            "name": "Stock Growth %",
            "displayFolder": "_Open & Close for Date Range",
            "expression": [
              "",
              "",
              "var result =  DIVIDE( [Last Close Value for Selected Period] - [First Open Value for Selected Period]  , [First Open Value for Selected Period] )",
              "",
              "RETURN ",
              "if( not ISBLANK(result), result )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "df3067fd-1778-41be-a323-2e13f2249860"
          },
          {
            "name": "Investment Growth",
            "displayFolder": "_Main Measures",
            "expression": "[Money Invested]   * (1 + [Stock Growth %] )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1dd71aa8-db53-40a6-9759-b20d3f99e1c5"
          },
          {
            "name": "Text Last 30 days",
            "displayFolder": "_Main Measures",
            "expression": "\"Last 30 days: \"",
            "lineageTag": "76a9fa53-7c71-4c74-9741-fe8c97fa78b8"
          },
          {
            "name": "Test Measure",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR CurrentDate = TODAY()",
              "VAR _range = DATESINPERIOD('Date'[Date], CurrentDate, -30, DAY)",
              "",
              "RETURN ",
              "    CALCULATE(",
              "        [Sum Close], ",
              "        _range",
              "    )",
              ""
            ],
            "lineageTag": "150ea5b7-bb49-4a9c-bbb5-bd54e0ce4dc8"
          },
          {
            "name": "Open/Close AVG Gain %",
            "displayFolder": "_Main Measures",
            "expression": [
              "",
              "  AVERAGEX(  ",
              "    fact_stock_price, ",
              "    DIVIDE( fact_stock_price[close] - fact_stock_price[open] , fact_stock_price[open] ) )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "02450b8e-8841-4655-990d-f2b8e678ead5"
          },
          {
            "name": "Symbol AVG Stock Growth % 30 days",
            "displayFolder": "_Open & Close for Date Range",
            "expression": [
              "",
              "",
              "CALCULATE (",
              "    AVERAGEX ( dim_stock, [Stock Growth %] ),",
              "    'Time Range'[Range Name] = \"30 Days\"",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ec7c2d75-b37d-4d23-9458-ef41bb41eb49"
          },
          {
            "name": "Symbol AVG Stock Growth % 90 days",
            "displayFolder": "_Open & Close for Date Range",
            "expression": [
              "",
              "",
              "CALCULATE (",
              "    AVERAGEX ( dim_stock, [Stock Growth %] ),",
              "    'Time Range'[Range Name] = \"90 Days\"",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "de005f2f-eaf1-4585-af45-0d4f1c32148d"
          },
          {
            "name": "Symbol AVG Stock Growth % 1Y",
            "displayFolder": "_Open & Close for Date Range",
            "expression": [
              "",
              "",
              "CALCULATE (",
              "    AVERAGEX ( dim_stock, [Stock Growth %] ),",
              "    'Time Range'[Range Name] = \"1Y\"",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dd24d880-3683-4fc2-9c6f-9f65f4d53965"
          },
          {
            "name": "Symbol AVG Stock Growth % 5Y",
            "displayFolder": "_Open & Close for Date Range",
            "expression": [
              "",
              "",
              "CALCULATE (",
              "    AVERAGEX ( dim_stock, [Stock Growth %] ),",
              "    'Time Range'[Range Name] = \"5Y\"",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8add77f3-f295-45fa-88dc-68fa1d141a81"
          },
          {
            "name": "Max MDT DateTime",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": "max('Data Updated DateTime'[MDT DateTime] ) // - TIME(6, 0, 0)",
            "formatString": "dd-mmm-yy hh:nn AM/PM",
            "lineageTag": "85aa8816-1449-48c7-99d2-32c808fffae3"
          },
          {
            "name": "Max UTC DateTime",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": "max('Data Updated DateTime'[UTC DateTime] )",
            "formatString": "dd-mmm-yy hh:nn AM/PM",
            "lineageTag": "e74412fb-6290-4151-b404-bb134c8d43c9"
          }
        ],
        "partitions": [
          {
            "name": "_Measure Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "tableopenbalnce",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fe5b1cf2e3f040d591817e3912831866"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "92e644d6-b8c5-44b1-a51a-a5c29ee82572",
            "sourceColumn": "Date[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "743965d0-f878-4030-aa91-4d84937a9310",
            "sourceColumn": "Date[Year]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f43b37e3-d52a-411f-9c07-5b9fff5f9a5f",
            "sourceColumn": "Date[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6b79968f-ba2d-4243-8386-e1d301979390",
            "sourceColumn": "Date[Month]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9d56042b-4adc-438a-8952-92426181cee7",
            "sourceColumn": "Date[Month Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a43766c0-4611-4f80-843c-0599b538a861",
            "sourceColumn": "Date[Day]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "95192cc0-1c46-4319-abae-55cb07d25f58",
            "sourceColumn": "Date[Month Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year-Quarter-Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d4934cf6-5cf5-4ce7-80bb-0656310313f2",
            "sourceColumn": "Date[Year-Quarter-Sort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week Last Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "53b5ed66-87e2-46a4-81dd-35e3c2ac1ff1",
            "sourceColumn": "Date[Week Last Day]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Date SID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ccece35e-5306-4f91-9206-c4192f531872",
            "sourceColumn": "Date[Date SID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsCurrentMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8df7599f-281e-44f8-a839-3c98502a6e34",
            "sourceColumn": "Date[IsCurrentMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter-Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "76e9d5f7-30d2-4f7e-bbb1-771c04c0e747",
            "sourceColumn": "Date[Quarter-Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year-Month Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cac32318-f6d2-45a9-8be0-ae145c817556",
            "sourceColumn": "Date[Year-Month Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6669837f-2dac-455b-9a29-7a61bcf2cfb1",
            "sourceColumn": "Date[Day of week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of week number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ab6e2be5-d97e-4cb7-986d-5f97a6b2c162",
            "sourceColumn": "Date[Day of week number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "d0439655-3da0-4587-8992-74fa30206e0a",
        "partitions": [
          {
            "name": "tableopenbalnce",
            "mode": "import",
            "source": {
              "expression": "FILTER(  all('Date') , SUM( fact_stock_price[open]) > 0  )",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Industry",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0954d324a4ae4f109192bc54ccd75342"
          }
        ],
        "columns": [
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "7916d7b8-2495-431c-8bc0-34db5a752af8",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Industry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "b0cddd2e-1535-4074-88eb-d7b4df97cf50",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "symbol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "033fd2e9-4754-4f1f-82b6-0f87421c196d",
            "sourceColumn": "[Value3]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Logo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "b4ffe442-6be1-4d86-9dc2-c35db8598b10",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "9e71cf9b-57c7-4675-84ba-df9b781952e8",
        "partitions": [
          {
            "name": "Industry",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "",
                "{",
                "    (0, \"No Industry\", \"VOO\", \"https://upload.wikimedia.org/wikipedia/commons/8/81/Vanguard.svg\"),",
                "    (4, \"Automotive\", \"TSLA\", \"https://upload.wikimedia.org/wikipedia/commons/b/bd/Tesla_Motors.svg\"),",
                "    (5, \"Automotive\", \"TM\", \"https://upload.wikimedia.org/wikipedia/commons/7/78/Toyota_Logo.svg\"),",
                "    (6, \"Automotive\", \"F\", \"https://upload.wikimedia.org/wikipedia/commons/3/3e/Ford_logo_flat.svg\"),",
                "    (1, \"Tech\", \"AAPL\", \"https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg\"),",
                "    (2, \"Tech\", \"MSFT\", \"https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg\"),",
                "    (3, \"Tech\", \"NVDA\", \"https://upload.wikimedia.org/wikipedia/commons/2/21/Nvidia_logo.svg\"),",
                "    (7, \"Finance\", \"JPM\", \"https://upload.wikimedia.org/wikipedia/commons/0/07/J_P_Morgan_Chase_Logo_2008_1.svg\"),",
                "    (8, \"Finance\", \"GS\", \"https://upload.wikimedia.org/wikipedia/commons/6/61/Goldman_Sachs.svg\"),",
                "    (9, \"Finance\", \"MS\", \"https://upload.wikimedia.org/wikipedia/commons/3/34/Morgan_Stanley_Logo_1.svg\")",
                "}",
                "",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "CG Time Intelligence",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "YTD",
              "expression": [
                "calculate( ",
                "    selectedmeasure(),",
                "    filter( 'Date' , 'Date'[Date] >=  date(year([NonBlank Close Date]) , 01 , 01 ) && 'Date'[Date] <= [NonBlank Close Date])",
                "    )"
              ]
            },
            {
              "name": "30 Days",
              "expression": [
                "calculate( ",
                "    selectedmeasure(),",
                "    FILTER( 'Date' , 'Date'[Date] >= [NonBlank Close Date]-30 && 'Date'[Date] <= [NonBlank Close Date])",
                "    )"
              ]
            },
            {
              "name": "90 Days",
              "expression": [
                "calculate( ",
                "    selectedmeasure(),",
                "    FILTER( 'Date' , 'Date'[Date] >= [NonBlank Close Date]-90 && 'Date'[Date] <= [NonBlank Close Date])",
                "    )"
              ]
            },
            {
              "name": "1Y",
              "expression": [
                "var  lastclosedate = [NonBlank Close Date]",
                "",
                "return",
                "calculate( ",
                "    selectedmeasure(),",
                "    FILTER( 'Date' , 'Date'[Date] >= date( year( lastclosedate)-1 , MONTH(lastclosedate), DAY(lastclosedate))   && 'Date'[Date] <= lastclosedate)",
                "    )"
              ]
            },
            {
              "name": "5Y",
              "expression": [
                "var  lastclosedate = [NonBlank Close Date]",
                "",
                "return",
                "calculate( ",
                "    selectedmeasure(),",
                "    FILTER( 'Date' , 'Date'[Date] >= date( year( lastclosedate)-5 , MONTH(lastclosedate), DAY(lastclosedate))   && 'Date'[Date] <= lastclosedate)",
                "    )"
              ]
            },
            {
              "name": "MAX",
              "expression": [
                "calculate( ",
                "    selectedmeasure()",
                "    )"
              ]
            }
          ]
        },
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58bd7963-bd75-4c73-b8d6-bad56afb1f03",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "e626e7fe-6696-4365-b10f-82875143dd06",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "258cb777-d3f9-46da-926d-d61747d8d9f2",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Time Range",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1c026d48e80d48b992c12b6928635dee"
          }
        ],
        "columns": [
          {
            "name": "Range Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "ee2b489a-b611-4eb7-9378-b5fed8bafd9c",
            "sortByColumn": "Sort Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sort Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "05ffe234-3905-4f7d-820d-8aac62287ca5",
            "sourceColumn": "[Value2]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6da39a24-e7db-430c-a179-df7343d4b2ae",
        "partitions": [
          {
            "name": "Time Range",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "{ ",
                "    (\"30 Days\",1),",
                "    (\"90 Days\",2),",
                "    (\"YTD\",3),",
                "    (\"1Y\",4),",
                "    (\"5Y\",5),",
                "    (\"MAX\",6) ",
                "}",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Data Updated DateTime",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UTC DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "14c6b1d8-1833-4d0a-9995-d553c2521846",
            "sourceColumn": "UTC DateTime",
            "summarizeBy": "none"
          },
          {
            "name": "MDT DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7970d6f0-ce59-4cb8-9de0-574e67fa3901",
            "sourceColumn": "MDT DateTime",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "00cd25cb-2997-40a2-9feb-e4510d05d5ee",
        "partitions": [
          {
            "name": "Data Updated DateTime",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #table(",
                "        {\"MDT DateTime\", \"UTC DateTime\"},",
                "        {",
                "            {",
                "                DateTimeZone.RemoveZone(DateTimeZone.LocalNow()),",
                "                DateTimeZone.RemoveZone(DateTimeZone.UtcNow())",
                "            }",
                "        }",
                "    ),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"UTC DateTime\", type datetime}, {\"MDT DateTime\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}